site_name: DSOL MANUAL
site_url: https://simulation.tudelft.nl/dsol/manual/
site_favicon: images/favicon.png
copyright: (c) 2002-2022 Delft University of Technology

theme:
  name: readthedocs
  navigation_depth: 1
    
markdown_extensions:
  - admonition

extra_css: 
  - css/custom.css
  
extra_javascript:
  - js/collapse_menu.js
    
nav:
  - Home: index.md
  - Getting started:
    - Installing Eclipse: getting-started/eclipse.md
    - Simulation theory: getting-started/dsol-project.md
    - DSOL documentation: https://simulation.tudelft.nl/dsol/latest/index.html
    - DSOL API: https://simulation.tudelft.nl/dsol/latest/apidocs/index.html
  - Simulation theory:
    - Introduction: theory/introduction.md
    