site_name: DSOL MANUAL
site_url: https://simulation.tudelft.nl/dsol/manual/
site_favicon: images/favicon.png
copyright: (c) 2002-2022 Delft University of Technology

theme:
  name: readthedocs
  navigation_depth: 1
    
markdown_extensions:
  - admonition

extra_css: 
  - css/custom.css
  
extra_javascript:
  - js/collapse_menu.js
    
nav:
  - Home: index.md
  - Getting started:
    - Installing Eclipse: 1-getting-started/eclipse.md
    - DSOL projects: 1-getting-started/dsol-project.md
    - DSOL technical docs: https://simulation.tudelft.nl/dsol/docs/latest/index.html
    - API dsol-core: https://simulation.tudelft.nl/dsol/docs/latest/dsol-core/apidocs/index.html
  - Simulation theory:
    - Introduction: 2-theory/introduction.md
  - DSOL basics:
    - Time in DSOL: 3-basics/time.md
    - Model structure: 3-basics/model-structure.md
    - Input parameters: 3-basics/input-parameters.md 
    - Random numbers: 3-basics/random-numbers.md
    - Stochastic distributions: 3-basics/stochastic-distributions.md
    - Output statistics: 3-basics/output-statistics.md
  - Advanced topics:
    - Distribution Parameters: 8-advanced/distribution-parameters.md
    - Custom InputParameter: 8-advanced/custom-parameter.md
    - Publish-Subscribe: 8-advanced/publish-subscribe.md
    - Naming Context: 8-advanced/naming-context.md
    